### ISSUE TITLE
[1.12.2] Having Resizing Potion installed breaks 'Step Assist' in some mods.

### ISSUE THREAD

**Issue by SonicX8000** [CammiePone/Resize-Potion#11]
Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 6
ArtemisLib-1.12.2-v1.0.4
conarm-1.12.2-1.2.3
Mantle-1.12-1.3.3.49
ProjectE-1.12.2-PE1.4.0
Resizing+Potion-r2.1
TConstruct-1.12.2-2.12.0.135

-----

Step Assist in some mods allows you to walk up a full block instead of it being a half block. For some reason... having Resizing Potion installed breaks some forms of the Step Assist.

The Gem Boots from ProjectE and some Construct's Armory Boots with the "High Stride" modifier has Step Assist which should let you walk up full blocks... only... you're unable to for some reason.

'Gem Boots' let's you walk up 1 Block, 'High Stride' let's you walk up 1 1/2 Blocks and 'High Stride II' let's you walk up 2 1/2 Blocks.

Removing Resizing Potion will allow both those items to work as intended which means I can walk up the blocks.

**Comment by CammiePone** [comment]
I think I know the problem. I'll get to fixing it soon

**Comment by SonicX8000** [comment]
Issue still exists in "resizingpotion-2.1.1" where the Step Assist from Construct's Armory & ProjectE's Gem Boots are still borked.

Other mods:
ArtemisLib-1.12.2-v1.0.4
conarm-1.12.2-1.2.3.4
Mantle-1.12-1.3.3.55
ProjectE-1.12.2-PE1.4.1
TConstruct-1.12.2-2.12.0.135

**Comment by A-UNDERSCORE-D** [comment]
Confirming this with FTB: Interactions. The offending line is https://github.com/CammiePone/Resize-Potion/blob/master/src/main/java/com/camellias/resizer/handlers/PotionHandler.java#L71

I'd suggest adding step height and storing that with an NBT tag on the player. That way you know how much to remove, rather than simply setting it

**Comment by HenryLoenwind** [comment]
What's your definition of "soon"?

**Comment by Saereth** [comment]
any update on this? We really love the mod but this is breaking for alot people using our pack.

**Comment by zabi94** [comment]
The latest version (currently pending on curseforge) should partially fix this.
Due to how step assist works, it _might_ be necessary to re-apply all step assist mechanics after a size change (eg: remove and re-equip botania's sash, or ProjectE boots). I didn't actually test this because of my time schedule, so any feedback is appreciated, both on whether this fix works and whether re-equipping is necessary

**Comment by Saereth** [comment]
awesome, thanks for the quick reply!
