### ISSUE TITLE
Idō incompatibility-ish

### ISSUE THREAD

**Issue by Spootikai** [CammiePone/Resize-Potion#21]
Idō backports 1.14 crouching/crawling/swimming mechanics to 1.12.2 
the player model does not shrink in these states when the shrink effect is applied.

**Comment by Spootikai** [comment]
ah it also keeps the camera at the normal 2 blocks

**Comment by zabi94** [comment]
Heads up: this mod only adds a potion that hooks into ArtemisLib's size changing mechanic, it isn't responsible for the actual resizing. The correct mod to report it to would be that. 

Anyways, a fix could technically be arranged, but the amount of work and coordination it would require is not worth it at this point.
While it still is the de-facto standard version for playing modded, 1.12 is now deprecated.

You might want to ask idō developers to fix compatibility with ArtemisLib instead, since they took the time to backport features they might be more interested, and with AL being a library it should be easier on their side.

**Comment by CammiePone** [comment]
@Spootikai alright, so that would be on Ido to add compatibility with ArtemisLib. I would recommend informing them of this bug, and asking them about adding the compatibility to the library. It would actually be less work for them to do the compatibility, than for me to attempt to add compatibility with ArtemisLib.
